### ISSUE TITLE
no module named requests

### ISSUE THREAD

**Issue by aiden04** [Sanix-Darker/Brute-Force-Login#20]
when running command "python3 -m app.main" in main folder I get an output saying 
`Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tingt\Desktop\Brute-Force-Login-master\app\main.py", line 6, in <module>
    from app.utils import *
  File "C:\Users\tingt\Desktop\Brute-Force-Login-master\app\utils.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`
I tried uninstalling and reinstalling requests, that didn't work so I tried uninstalling and reinstalling requirements and that still didn't work. Any ideas?

**Comment by nu11secur1ty** [comment]
```bash
pip3 install -r requierements.txt
```
