### ISSUE TITLE
error URLs

### ISSUE THREAD

**Issue by githubcom13** [Sanix-Darker/Brute-Force-Login#8]
Hi,
there is an error on the URLs provided.

sample: [http://ranchmanageropen.com/community/member.php?action=login](url)

```
MacBook-Pro:Brute-Force-Login-master nic$ python main.py

[+] # -------------------------------------------
[+] # | __ )  |  ___| | |
[+] # |  _ \  | |_    | |
[+] # | |_) | |  _|   | |___
[+] # |____/  |_|     |_____| v0.0.2
[+] # => Brute Force Login <=                     #
[+] # By S@n1x d4rk3r                             #
[+] # #############################################
[+] Select a mode for detecting fields:
[+] 1-) Automatic mode (Will get all necessary field and proceed)
[+] 2-) Manual mode (you will provide necessary information before continue)
[+] -
[+] 0-) Stop the program
[+] Choice: 2
[+] Manual mode selected
[+] After inspecting the LOGIN <form />, please fill here :

[+] Enter the target URL (it's the 'action' attribute on the Login form):https://sample.com/member.php?action=login
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    main()
  File "main.py", line 156, in main
    elif mode == 2: manual_mode()
  File "main.py", line 107, in manual_mode
    url = input("\n[+] Enter the target URL (it's the 'action' attribute on the Login form):")
  File "<string>", line 1
    https://sample.com/member.php?action=login
         ^
SyntaxError: invalid syntax
MacBook-Pro:Brute-Force-Login-master nic$
```

**AND** 

```
MacBook-Pro:Brute-Force-Login-master nic$ python main.py

[+] # -------------------------------------------
[+] # | __ )  |  ___| | |
[+] # |  _ \  | |_    | |
[+] # | |_) | |  _|   | |___
[+] # |____/  |_|     |_____| v0.0.2
[+] # => Brute Force Login <=                     #
[+] # By S@n1x d4rk3r                             #
[+] # #############################################
[+] Select a mode for detecting fields:
[+] 1-) Automatic mode (Will get all necessary field and proceed)
[+] 2-) Manual mode (you will provide necessary information before continue)
[+] -
[+] 0-) Stop the program
[+] Choice: 2
[+] Manual mode selected
[+] After inspecting the LOGIN <form />, please fill here :

[+] Enter the target URL (it's the 'action' attribute on the Login form):sample.com/member.php?action=login
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    main()
  File "main.py", line 156, in main
    elif mode == 2: manual_mode()
  File "main.py", line 107, in manual_mode
    url = input("\n[+] Enter the target URL (it's the 'action' attribute on the Login form):")
  File "<string>", line 1
    sample.com/member.php?action=login
                         ^
SyntaxError: invalid syntax
MacBook-Pro:Brute-Force-Login-master nic$
```

**Comment by Sanix-Darker** [comment]
![Working](https://user-images.githubusercontent.com/22576758/74375878-6b377b80-4de1-11ea-896c-742dadc47462.png)

Your URL is working properly on my side, make sure you're using Python 3.x

**Comment by githubcom13** [comment]
Thank you, yes you are right my default environment was version 2.7
I just did a new test with version 3.8.1 and I get this error.
I'm trying to test your tool on a Mybb forum

```
[+] # -------------------------------------------
[+] # | __ )  |  ___| | |
[+] # |  _ \  | |_    | |
[+] # | |_) | |  _|   | |___
[+] # |____/  |_|     |_____| v0.0.2
[+] # => Brute Force Login <=                     #
[+] # By S@n1x d4rk3r                             #
[+] # #############################################
[+] Select a mode for detecting fields:
[+] 1-) Automatic mode (Will get all necessary field and proceed)
[+] 2-) Manual mode (you will provide necessary information before continue)
[+] -
[+] 0-) Stop the program
[+] Choice: 2
[+] Manual mode selected
[+] After inspecting the LOGIN <form />, please fill here :

[+] Enter the target URL (it's the 'action' attribute on the Login form):https://(hidden).com/member.php?action=login

[+] Enter the User Field  (it's the 'name' attribute on the Login form for the username/email):username

[+] Enter the Password field  (it's the 'name' attribute on the Login form for the password):password
[+] Connecting to: https://(hidden).com/member.php?action=login......

Traceback (most recent call last):
  File "main.py", line 161, in <module>
    main()
  File "main.py", line 155, in main
    if mode == 1: automatic_mode()
  File "main.py", line 130, in automatic_mode
    main()
  File "main.py", line 156, in main
    elif mode == 2: manual_mode()
  File "main.py", line 114, in manual_mode
    try_connection(url, user_field, password_field)
  File "main.py", line 94, in try_connection
    for user in USERS:
NameError: name 'USERS' is not defined
MacBook-Pro:Brute-Force-Login-master nic$
```

**Comment by Sanix-Darker** [comment]
You're not suppose to have this issue, have you change the code ?

The "not defined" variable have been declared at line : `21` and line `22` like this : 

```python
# Getting list of user to test with
USERS = open_ressources('./ressources/users.txt')
```
